gridcf/gct

README.md

At some pithy introduction to the GCT itself.

Update the README to make it clear this is not the Globus Toolkit.

---

.travis.yml
packaging/git-dirt-filter
travis-ci/setup_tests.sh
travis-ci/test_inside_docker.sh
travis-ci/test_unpriv_inside_docker.sh

In order to keep one of the tests from timing Travis-CI out, I had to decrease the timeout of the test.
Tests need to run as non-root or various authentication things will fail.

Add Travis-CI config and scripts

---

travis-ci/run_task_inside_docker.sh

In case we run into the same problem we had with libffi for the other libraries the xio udt driver build might try to download.

Install other devel libs for the xio udt driver so the build won't try to download them

---

gram/jobmanager/source/globus-job-manager.8
gram/jobmanager/source/globus-job-manager.txt
gram/jobmanager/source/globus_gram_job_manager_config.c
gridftp/server/src/globus-gridftp-server-options.txt
gridftp/server/src/globus-gridftp-server.8
gridftp/server/src/globus_i_gfs_config.c
myproxy/source/man/myproxy-server.config.5
myproxy/source/myproxy-server.config
myproxy/source/myproxy_server_config.c

Disable usage statistics reporting by default

---

travis-ci/upload_source_tarballs.sh

In response to https://github.com/gridcf/gct/commit/a41403cc6b3079477b313bb8bc298021181412cd#commitcomment-30579850

Don't delete big gct tarball

---

gsi/cert_utils/source/configure.ac
gsi/cert_utils/source/programs/grid-cert-request.in
packaging/debian/globus-gsi-cert-utils/debian/changelog.in
packaging/fedora/globus-gsi-cert-utils.spec

Bug reported to Redhat/Fedora bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1640939

Fix broken subject in grid-cert-request

---

gram/client/source/configure.ac
gram/client/source/globus_gram_client.c
packaging/debian/globus-gram-client/debian/changelog.in
packaging/debian/globus-gram-client/debian/copyright
packaging/fedora/globus-gram-client.spec

globus_gram_client.c:3520: warning: argument 'job_contact' from the
argument list of globus_gram_client_job_contact_free has muliple
@param documentation sections

Fix doxygen warning

---

packaging/debian/gsi-openssh/debian/patches/hpn_isshd-gsi.7.5p1c.patch

This PR was created in response to issue #85.

Change GSSAPITrustDNS default to no

---

gridftp/net_manager/configure.ac
gridftp/net_manager/python/Makefile.am
packaging/debian/globus-net-manager/debian/changelog.in
packaging/debian/globus-net-manager/debian/copyright
packaging/fedora/globus-net-manager.spec

Addresses Issue #87. See that issue for details.

Check python-config for --embed flag (python 3.8 compatibility)

---

INSTALL.txt

Add INSTALL.txt, that outlines how to build the software by hand.

Document install procedure

---

gsi/gridmap_eppn_callout/configure.ac
gsi/gridmap_eppn_callout/globus_gridmap_eppn.c
packaging/debian/globus-gridmap-eppn-callout/debian/changelog.in
packaging/fedora/globus-gridmap-eppn-callout.spec

This is the same PR as https://github.com/globus/globus-toolkit/pull/126
I was advised by @msalle to make the PR also here, but i hvae no idea how this will conflict with any later backports/rebases
@msalle also mentioned to add some documentation, but i'm a bit clueless where i should do so

Eppn force map

---

packaging/debian/globus-simple-ca/debian/changelog.in
packaging/debian/globus-simple-ca/debian/globus-simple-ca.postinst
packaging/fedora/globus-simple-ca.spec

This addresses the failure discussed here:
https://github.com/gridcf/gct/pull/90#issuecomment-530917904

Check that hostname command succeeds in post install script

---

INSTALL.md

Sorry for the extra noise, but the markup came out wrong and needed an update.

Updated markup

---

gridftp/server/src/configure.ac
gridftp/server/src/globus_i_gfs_data.c
packaging/debian/globus-gridftp-server/debian/changelog.in
packaging/fedora/globus-gridftp-server.spec

Restore log transfer functionality that was accidentally removed

---

gass/copy/source/globus-url-copy.1
gass/copy/source/globus-url-copy.txt

This solves
https://github.com/gridcf/gct/issues/112

Document environment variables in globus-url-copy manpage

---

.travis.yml

Remove CentOS 6 from the automated tests run on Travis CI.

Don't test on EL 6

---

gsi/gssapi/source/configure.ac
gsi/gssapi/source/library/globus_i_gsi_gss_utils.c
gsi/gssapi/source/library/init_sec_context.c
packaging/debian/globus-gssapi-gsi/debian/changelog.in
packaging/fedora/globus-gssapi-gsi.spec

See https://github.com/dCache/dcache/issues/5939.

Compatibility with the dcache server implementation

---

gsi/gssapi/source/configure.ac
gsi/gssapi/source/library/init_sec_context.c
packaging/debian/globus-gssapi-gsi/debian/changelog.in
packaging/fedora/globus-gssapi-gsi.spec

Better logic for TLS 1.3 special handling

---

common/source/configure.ac
common/source/library/globus_options.c
gsi/cert_utils/source/configure.ac
gsi/cert_utils/source/library/globus_gsi_cert_utils_error.c
packaging/debian/globus-common/debian/changelog.in
packaging/debian/globus-gsi-cert-utils/debian/changelog.in
packaging/fedora/globus-common.spec
packaging/fedora/globus-gsi-cert-utils.spec

globus-gsi-cert-utils: Add missing comma
- Fixes #182.
globus-common: Simplify code
- After discussing this code during the review of a preivous PR, I realized it could be simplified further.

Minor fixes

---

.github/workflows/build-test-deploy.yml
README.md
travis-ci/run_task_inside_docker.sh

* CentOS Stream 8 and 9
* RockyLinux 8

Enable additional CI build targets

---

gsi/gss_assist/source/test/gss-assist-auth-test.pl
gsi/gssapi/source/library/globus_gsi_gss_constants.h
gsi/gssapi/source/library/globus_i_gsi_gss_utils.c
gsi/gssapi/source/library/init_sec_context.c

Fixes https://github.com/gridcf/gct/issues/195

Don't assume that TLS 1.3 returns exactly two session tickets

---

gridftp/server/src/configure.ac
gridftp/server/src/test/cmp_alias_ent_test.c
packaging/debian/globus-gridftp-server/debian/changelog.in
packaging/fedora/globus-gridftp-server.spec

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2146585

Fix buffer overflow in test
