gridcf/gct

- .travis.yml
- Makefile.am
- make-source-tarballs.sh
- travis-ci/make_source_tarballs.sh
- travis-ci/setup_tests.sh
- travis-ci/test_inside_docker.sh
Add a script that builds a full set of source tarballs for the GCT components (except gridftp-hdfs). Can be run standalone easily, but added config to run via Travis: https://travis-ci.org/matyasselmeci/gct/builds/308697470
> Make source tarballs in Travis

- gram/jobmanager/source/startup_socket.c
- gram/jobmanager/source/test/jobmanager/rsl_size_test/globus-gram-job-manager-rsl-size-test.pl.in
https://github.com/globus/globus-toolkit/pull/29
Workaround non-implemented features on GNU/Hurd.
> Socket buffer size

- gridftp/server/src/globus-gridftp-server-setup-chroot
https://github.com/globus/globus-toolkit/pull/32
Fixes broken tests on hurd and freebsd.
> Add more unames

- gram/jobmanager/source/test/gram-test-wrapper.in
https://github.com/globus/globus-toolkit/pull/42
If there is a proxy file around the first test fails. By moving the call to grid-proxy-destroy to before starting the personal gatekeeper, this is fixed.
(Only the first test fails because when the second test is run the grid-proxy-destroy from the first test has removed the proxy.)
> Move grid-proxy-destroy call to before starting personal gatekeeper

- gridftp/server-lib/src/globus_gridftp_server_control.c
- gridftp/server-lib/src/globus_gridftp_server_control.h
- gridftp/server-lib/src/globus_gridftp_server_control_attr.c
- gridftp/server-lib/src/globus_gridftp_server_control_commands.c
- gridftp/server-lib/src/globus_i_gridftp_server_control.h
- gridftp/server/src/globus_i_gfs_config.c
- gridftp/server/src/globus_i_gfs_control.c
https://github.com/globus/globus-toolkit/pull/97
This pull request is forwarded from the developers of DPM (disk pool manager). Their description of the proposed change follows. The pull request is created using the patches mentioned below. The original author of the text below is @andrea-manzi.
"While investigating an issue affecting one DPM in production we have realized that a commit in globus some time ago has broken the gridftp redirection implementation when using IPv6.
We don't know exactly when this was pushed to EPEL, but we are seeing this problem only now as sites are starting to use IPv6 and enabling gridftp redirection to go …
> Adds an optional IPv6 address to EPSV response

- gridftp/server-lib/src/globus_gridftp_server_control.h
- gridftp/server-lib/src/globus_gridftp_server_control_accessors.c
- gridftp/server/src/globus_gridftp_server.h
- gridftp/server/src/globus_i_gfs_control.c
- gridftp/server/src/globus_i_gfs_control.h
- gridftp/server/src/globus_i_gfs_data.c
https://github.com/globus/globus-toolkit/pull/98
This pull request is forwarded from the developers of DPM (disk pool manager). Their description of the proposed change follows. The pull request is created using the patches mentioned below. The original author of the text below is @andrea-manzi.
"Similarly given that we didn't get any answer from the ticket we opened to globus,
We would like to understand if it's possible to patch the same packages in order for us to stop including the gridftp internal structures in our dpm-dsi builds and thus freeing the strict dep between
globus-gridftp-server and dpm-dsi.
Andrey prepared 2 patches also …
> Get command string

- gsi/gssapi/source/library/globus_i_gsi_gss_utils.c
https://github.com/globus/globus-toolkit/pull/106
With the update of globus-gssapi-gsi to version 2.15, the option SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS is no longer used.
Users of the Globus Toolkit report that this breaks interaction with Bestman.
See https://its.cern.ch/jira/browse/DMC-974 and the comments to the EPEL update ticket https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-b1d8b4aed9 for details.
This pull request puts the use of the option back to restore the lost functionality.
> Put back use of SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS

- gridftp/server-lib/src/globus_gridftp_server_control.c
https://github.com/globus/globus-toolkit/pull/117
If the client opens a connection and immediately closes it before the server
can write the "220 ... ready." banner, the server process gets gets stuck in
globus_cond_wait() in globus_gridftp_server.c.
If the client opens a connection and immediately closes it before the gridftp server can write the "220 ... ready." banner, the server process gets gets stuck in globus_cond_wait() in globus_gridftp_server.c.
Following through the code:
1. --Client connects to server--
2. globus_l_gsc_open_cb() registers a write for the FTP banner and sets callback globus_l_gsc_220_write_cb()
3. --Client …
> Terminate the connection if server fails to write the 220 banner

- gridftp/server/src/globus-gridftp-server.8
- gridftp/server/src/globus_i_gfs_config.c
https://github.com/globus/globus-toolkit/pull/118
Instead of ignoring all files with a . in the name in /etc/config.d, only ignore backup files (.bak, ~) and packaging files (.rpmsave, etc.).
> Gridftpd configd files

- travis-ci/run_task_inside_docker.sh
This should fix the build failures from the libffi tarball.
> Install libffi-devel if we're building UDT

- travis-ci/travis.yml
Useful for it to be in the same dir as all our other travis stuff and also not be hidden.
> Add symlink to .travis.yml for convenience

- gsi/gssapi/source/configure.ac
- gsi/gssapi/source/library/globus_i_gsi_gss_utils.c
- packaging/debian/globus-gssapi-gsi/debian/changelog.in
- packaging/fedora/globus-gssapi-gsi.spec
The GSI GSSAPI currently does not work with TLS 1.3. Use TLS1_2_VERSION instead of TLS_MAX_VERSION as the maximum TLS protocol version until it has been ported.
This is a workaround for #43 but not a fix. The proper fix would be to make the code work with TLS 1.3 rather than avoiding the issue by limiting the TLS version to <= 1.2. Hopefully that will eventually happen.
> Avoid TLS 1.3 for now

- configure.ac
- travis-ci/make_source_tarballs.sh
[v1] -> v2:
- version number is kept as is
- default prefix is kept as is
[v1]: https://github.com/gridcf/gct/pull/11
> Also create gct source installer tarball v2

- gass/copy/source/configure.ac
- gass/copy/source/test/Makefile.am
- gass/copy/source/test/guc-cc-fast.pl
- gass/copy/source/test/guc-cc-p2.pl
- gass/copy/source/test/guc-cc-p4.pl
- gass/copy/source/test/guc-cc-stripe-p4.pl
- gass/copy/source/test/guc-cc-stripe.pl
- gass/copy/source/test/guc-cc.pl
- packaging/debian/globus-gass-copy/debian/changelog.in
- packaging/fedora/globus-gass-copy.spec
The guc-cc.pl in the globus-gass-copy package take a long time to run on slow computers, and after the increase of the RSA key size used for testing it takes even longer.
The official Debian build servers have a test to detect stuck builds that kills a build if it hasn't printed anything to stdout/stderr for 150 minutes (2½ hours). When running the test suite the output from the test is redirected to various log files and only at the end of the test a status is written to stdout.
With the longer execution time due to the larger key size, the execution time of the guc-cc.pl test exceeds 2½ hours on the slower Debian build servers (has happened on hppa, armhf and mips builds).
This PR splits the guc-cc.pl into 6 smaller tests. The same tests are performed as with the original version, but …
> Split guc-cc.pl test into smaller tests

- gsi/sysconfig/source/configure.ac
- gsi/sysconfig/source/test/system-config-test.pl
- packaging/debian/globus-gsi-sysconfig/debian/changelog.in
- packaging/fedora/globus-gsi-sysconfig.spec
In Perl the exit code of an external process is the value of $? shifted 8 bits to the right. This is done correctly everywhere in the code except for in one file where the shift is consistently done in the wrong direction. This PR fixes this issue.
> Correct bitshift direction in perl test file

- gram/jobmanager/scripts/configure.ac
- packaging/debian/globus-gram-job-manager-scripts/debian/changelog.in
- packaging/fedora/globus-gram-job-manager-scripts.spec
Using LT_INIT in configure.ac results in the configure script checking for things that are not relevant for an architecture independent package, like the presence of a C compiler.
The other architecture independent packages already correctly do not use LT_INIT:
* gram/jobmanager/auditing/source/configure.ac
* gram/jobmanager/lrms/slurm/source/configure.ac
* gram/jobmanager/lrms/condor/source/configure.ac
* gsi/simple_ca/source/configure.ac
> Architecture independent package should not depend on libtool

- gsi/gssapi/source/configure.ac
- gsi/gssapi/source/library/gsi.conf
- packaging/debian/globus-gssapi-gsi/debian/changelog.in
- packaging/fedora/globus-gssapi-gsi.spec
The old GT upstream changed the default minimum TLS version form 1.0 to 1.2 in their globus-gssapi-gsi version 13.9 (merged into GCT as our version 14.6).
There have been reports that this causes compatibility issues with some servers used in production in WLCG.
* https://ggus.eu/index.php?mode=ticket_info&ticket_id=137130
* https://mailman.egi.eu/pipermail/gt-eos/2018-September/000178.html
It was suggested that this change should be reverted, at least temporary. This PR sets the minimum TLS version to 1.0 in the gsi.conf configuration file.
> Allow TLS 1.0/1.1

- gram/jobmanager/source/configure.ac
- gram/jobmanager/source/gram.logrotate.in
- packaging/debian/globus-gram-job-manager/debian/changelog.in
- packaging/fedora/globus-gram-job-manager.spec
This addresses failures to start logrotate on newer releases that requires the su option when the directory containing the files to be rotated have less strict access permissions:
```
● logrotate.service - Rotate log files
Loaded: loaded (/lib/systemd/system/logrotate.service; static; vendor preset: enabled)
Active: failed (Result: exit-code) since Wed 2019-02-13 15:40:11 CET; 46min ago
Docs: man:logrotate(8)
man:logrotate.conf(5)
Process: 290 ExecStart=/usr/sbin/logrotate /etc/logrotate.conf (code=exited, status=1/FAILURE)
Main PID: 290 (code=exited, status=1/FAILURE)
feb 13 15:40:02 debian-unstable systemd[1]: Starting Rotate log files...
feb 13 15:40:09 debian-unstable logrotate[290]: error: skipping "/var/log/globus/gram_*.log" because parent directory has insecure permissions (It's …
```
> Add su option to logrotate file

- travis-ci/make_source_tarballs.sh
A user ran into this while trying to use the script on a Mac.
> Fix sed invocation on mac

- gridftp/server/src/configure.ac
- packaging/debian/globus-gridftp-server/debian/changelog.in
- packaging/debian/globus-xio-gsi-driver/debian/changelog.in
- packaging/debian/globus-xio-gsi-driver/debian/copyright
- packaging/fedora/globus-gridftp-server.spec
- packaging/fedora/globus-xio-gsi-driver.spec
- xio/drivers/gsi/configure.ac
The documentation link update mostly changed files in packaging/, but it did change two files in the sources. Bump versions for those.
> Update documentation links to always point to the latest documentation

- gram/gatekeeper/source/init/globus-gatekeeper-lsb.in
- gsi/simple_ca/source/grid-ca-sign.in
Hello guys,
I have encountered an error that `grid-ca-sign` can not find existing cert like below:
And when I checked the source code and  added some debug codes, I found there is a mistaken `sed` expression:
sed -e "s|subject= *|/|" -e "s|,|/|g"
The cert subject in cert.pem begins with "subject= /O=...". However, the sed expression will process this line incorrectly with one more "/" before the result like "//O=...", which will never match the "${req_subj}" starting with "/O=...". So the `if` expression will never work.
And  I just simply delete the "/" and the new `sed` expression is as below:
sed -e "s|subject= *||" -e "s|,|/|g"
Hope this will help!
Thank you.
> Fix openssl output format issue in sample-ca and gatekeeper startup script bug

- gsi/gssapi/source/library/init_sec_context.c
In gss_init_sec_context(), if globus_i_gsi_gss_handshake() returns an
error, the code attempts to fetch the output_token (if anyy) twice.
First in gss_init_sec_context() and again in gss_delete_sec_context().
The second fetch clobbers any data from the first fetch, so the client
never sends it.
The fix is to not pass output_token to gss_delete_sec_context() if it
already contains data.
> Keep peers in sync after SSL handshake failure in gssapi.

- Doxyfile.in
- configure.ac
- doxygen/index.dox.in
This adds a HTML header for the HTML API documentation created by doxygen which gets the "current" tag (i.e. what `git describe --tags` prints out, see DESCRIPTION in `git-describe(1)` for details) inserted after the "Globus" version number as `(tag: <CURRENT_TAG>)`.
The top of the API docs will then look like this:
...when `HEAD` doesn't point to a tagged version or just show a tag (e.g. `v6.2.20190226`) after `(tag: ` otherwise.
This PR derives from the discussion in https://github.com/gridcf/gct-docs/pull/9.
****
@matyasselmeci @ellert @msalle 
Could you please have a look into my modifcations to `configure.ac` and `Makefile.am`. I'm actually not really familiar with that stuff and just tried to "imitate" what saw in the files.
Instead of the `sed` command in the Makefile we could …
> Also use current tag in API documentation created by doxygen.

- gsi/cert_utils/source/programs/grid-cert-info.in
- gsi/cert_utils/source/programs/grid-change-pass-phrase.in
- packaging/debian/gridftp-hdfs/debian/README
- packaging/debian/gsi-openssh/debian/README
This fixes the remaining old document references from the list on https://github.com/gridcf/gct/issues/12#issuecomment-437045059.
****
Regarding the document from the old www-unix.globus.org site, looking into
https://web.archive.org/web/20100209082809/http://www-unix.globus.org/toolkit/docs/4.0/admin/docbook/ch05.html#s-prewsaa-env
https://gridcf.org/gct-docs/latest/gsic/pi/index.html#gsic-pi-env seems to
be the appropriate replacement.
> Update additional old document references

- common/source/configure.ac
- common/source/library/Makefile.am
- common/source/library/globus_module.c
- common/source/library/globus_thread.c
- common/source/library/globus_thread.h
- gsi/proxy/proxy_core/source/configure.ac
- gsi/proxy/proxy_core/source/library/globus_gsi_proxy_handle.c
- packaging/debian/globus-common/debian/changelog.in
- packaging/debian/globus-gsi-proxy-core/debian/changelog.in
- packaging/fedora/globus-common.spec
- packaging/fedora/globus-gsi-proxy-core.spec
This PR was triggered by SUSY adding -flto to their default compilation/linking flags.
The PR also removes some redundant "extern" from function declarations/definitions.
> Make symbol versioning work with link time optimization (LTO)

- gass/copy/source/configure.ac
- gass/copy/source/globus-url-copy.1
- gass/copy/source/globus-url-copy.txt
- packaging/debian/globus-gass-copy/debian/changelog.in
- packaging/fedora/globus-gass-copy.spec
Until we find a way to "fix" the problem described in #62 w/o breaking other functionality in the GridFTP server and client(s) this PR puts a warning into the guc manpage which - together with the apparently known fact (as per #69) that dCache does not support data channel encryption - hopefully prevents user from falling into that trap.
****
@ellert 
* I changed the text version of the manpage and the manpage directly, is there a tool I could use instead?
* Does this change also require a version number change for the gass-copy packages (in the spec and debian packaging files)? I'd say yes, but am unsure. If you agree, I can add these changes to this PR.
> Document guc/dcpriv behaviour with servers not supporting DC encryption

- gridftp/server/src/configure.ac
- gridftp/server/src/globus_i_gfs_data.c
- gridftp/server/src/test/sharing_allowed_test.c
- packaging/debian/globus-gridftp-server/debian/changelog.in
- packaging/fedora/globus-gridftp-server.spec
See discussion in #95 and #96.
> Avoid unknown secondary groups in test. Causes failures on launchpad.

- packaging/debian/globus-gsi-sysconfig/debian/changelog.in
- packaging/debian/globus-gsi-sysconfig/debian/libglobus-gsi-sysconfig1.install
- packaging/debian/globus-gsi-sysconfig/debian/rules
- packaging/fedora/globus-gsi-sysconfig.spec
There isn't much point to globus-gsi-sysconfig providing an empty /etc/grid-security/certificates directory, and putting it in the package causes problems for people that already have it, e.g. as a symlink to a shared filesystem.
> Don't package /etc/grid-security/certificates

- gsi/gssapi/source/configure.ac
- gsi/gssapi/source/library/gsi.conf
- packaging/debian/globus-gssapi-gsi/debian/changelog.in
- packaging/fedora/globus-gssapi-gsi.spec
Following @maarten-litmaath's comment on #55, that the setting for what TLS versions are enabled by default could now be restored to only allow 1.2, I have created this PR to do that.
A similar question. What about the change in #19. Can that be reverted too now? Or is it still relevant?
> Disallow TLS 1.0/1.1 by default again

- Makefile.am
This fixes https://github.com/gridcf/gct/issues/118
There are probably a few other places where we should bail out with a non-zero
exit value but this certainly fixes the main ones.
> On errors let make return with non-zero exitvalue

- gsi/cert_utils/source/configure.ac
- gsi/cert_utils/source/programs/grid-cert-info.in
- packaging/debian/globus-gsi-cert-utils/debian/changelog.in
- packaging/fedora/globus-gsi-cert-utils.spec
Old:
$ grid-cert-info -subject -issuer
/DC=org/DC=terena/DC=tcs/C=SE/O=Uppsala universitet/CN=Mattias Ellert mel03009@user.uu.se
C=NL,ST=Noord-Holland,L=Amsterdam,O=TERENA,CN=TERENA eScience Personal CA 3
New:
$ ~/grid-cert-info -subject -issuer
/DC=org/DC=terena/DC=tcs/C=SE/O=Uppsala universitet/CN=Mattias Ellert mel03009@user.uu.se
/C=NL/ST=Noord-Holland/L=Amsterdam/O=TERENA/CN=TERENA eScience Personal CA 3
I.e. issuer uses the same format as subject. (As it used to be with older openssl versions.)
> Fix format for grid-cert-info -issuer

- common/source/configure.ac
- packaging/debian/globus-common/debian/changelog.in
- packaging/fedora/globus-common.spec
Fedora recently implemented LTO as default.
Fedora only adds the -flto flag to CFLAGS and not to both CFLAGS and LDFLAGS.
This update adapts the LTO detection for this.
> Check for LTO use in CFLAGS instead of LDFLAGS

- gsi/gss_assist/source/programs/grid-mapfile-add-entry.8
- gsi/gss_assist/source/programs/grid-mapfile-add-entry.in
- gsi/gss_assist/source/programs/grid-mapfile-add-entry.txt
When using gtc and EUDAT B2STAGE, the users may not be connected to the unix users in the machine (e.g. if authorization uses OpenID tokens).
I added an option to allow modification of the gridmap file even if the unix user does not exist (-f -- force)
> Add force option if the users do not exist in the machine (needed for e.g. EUDAT B2STAGE)

- gridftp/server-lib/src/configure.ac
- gridftp/server-lib/src/globus_gridftp_server_control_commands.c
- packaging/debian/globus-gridftp-server-control/debian/changelog.in
- packaging/debian/globus-gridftp-server-control/debian/copyright
- packaging/fedora/globus-gridftp-server-control.spec
Title says it all.
Not a big change, but from now on the Globus GridFTP server should use the exact example message for a response to `EPSV` from [RFC 2428](https://tools.ietf.org/html/rfc2428), although the difference to a response to `PASV` could be already seen from the differences in the actual data part of the response (e.g. `(1,2,3,4,195,80)` (in response to `PASV`) and `(|||50000|)` (in response to `EPSV`)).
The difference to RFC 2428 was noticed during testing UberFTP 2.9-Beta against a Globus GridFTP server 13.20. UberFTP 2.9-Beta uses `EPSV` and `EPRT` by default (both commands are compatible with IPv4 and IPv6 address families) instead of `PASV` and `PORT` .
@msalle, @ellert: Sorry, but I'm again unsure about what to change in addition (major, minor version of …
> gridftp: Use example message from RFC 2428 for response to EPSV

- gsi/gssapi/source/library/init_sec_context.c
When globus_i_gsi_gss_handshake() indicates that the SSL handshake has
completed successfully, the check for a final output payload to send is
faulty. It checks output_token before the data has been copied into that
buffer. Instead, it needs to look at context->gss_wbio.
This bug puts the client and server out of sync, dooming the connection.
> Fix output payload check in gss_init_sec_context() after SSL handshake.

- gram/jobmanager/scheduler_event_generator/source/configure.ac
- gram/jobmanager/scheduler_event_generator/source/globus-scheduler-event-generator-admin.in
- packaging/debian/globus-scheduler-event-generator/debian/changelog.in
- packaging/fedora/globus-scheduler-event-generator.spec
Even though there is a comment in the admin script that says:
the admin script is not in sync with the init script.
This commit corrects this.
The admin script ignored the GLOBUS_SEG_PIDFMT setting in the
sysconfig file that the init script uses. With the default value they
still did the same, and there is usually no need to change the
default, so it usually worked anyway.
> Keep admin script in sync with init script

- README.md
This change is a combined effort with https://github.com/gridcf/gridcf.github.io/pull/13 and adds a reference of the GCT documentation to the [README.md](https://github.com/gridcf/gct/blob/master/README.md).
If you agree with the changes, this can be merged right now because it is not related to the upcoming release on 2020-12-24.
> Reference the GCT documentation and rephrase description

- myproxy/source/myproxy_get_delegation.c
> exit with error if voms-proxy-init fails

- myproxy/source/VERSION
- myproxy/source/configure.ac
- myproxy/source/myproxy.init.sles
- myproxy/source/myproxy_server.c
- myproxy/source/systemd/myproxy-server.conf
- myproxy/source/systemd/myproxy-server.service
- packaging/debian/myproxy/debian/changelog.in
- packaging/fedora/myproxy.spec
Filesystem Hierarchy Standard 3.0 says about /var/run:
"This directory was once intended for system information data
describing the system since it was booted. These functions have been
moved to /run."
Using /var/run in systemd unit files and tmpfiles.d config files
results in warnings in the logs:
Dec 23 12:42:25 localhost.localdomain systemd[1]: /usr/lib/systemd/system/myproxy-server.service:16: PIDFile= references a path below legacy directory /var/run/, updating /var/run/myproxy-server/myproxy.pid → /run/myproxy-server/myproxy.pid; please update the unit file accordingly.
/usr/lib/tmpfiles.d/myproxy-server.conf:1: Line references path below legacy directory /var/run/, updating /var/run/myproxy-server → /run/myproxy-server; please update the tmpfiles.d/ drop-in file accordingly.
> Update default run directory from /var/run to /run

- common/source/test/globus_test_tap.h
- gridftp/net_manager/attr/destroy.c
- gridftp/net_manager/attr/init.c
- gridftp/net_manager/context/destroy.c
- gridftp/net_manager/context/init.c
- gridftp/net_manager/test/globus_test_tap.h
- gsi/gss_assist/source/read_vhost_cred_dir.c
- gsi/gssapi/source/library/read_vhost_cred_dir.c
...by avoiding file names for the `\file` command in the files
changed with this commit. See https://www.doxygen.nl/manual/commands.html#cmdfile
for details.
Fixes #109.
> Fix name matching for Doxygen

- travis-ci/upload_source_tarballs.sh
This is the actual machine that hosts repo.gridcf.org.  We can't SFTP to
that alias because it's a CloudFlare redirect and, according to my
comment, "doesn't properly handle SSH".
The hosting duty for the OSG repos has moved to a different machine so
repo.opensciencegrid.org no longer points to the machine we used to
upload to.  Upload to hcc-osg-repo.unl.edu instead.
> Upload to "hcc-osg-repo.unl.edu"

- gass/copy/source/configure.ac
- gass/copy/source/globus_url_copy.c
- packaging/debian/globus-gass-copy/debian/changelog.in
- packaging/fedora/globus-gass-copy.spec
```
globus-url-copy -list gsiftp://localhost/~
gsiftp://localhost/~
Segmentation fault (core dumped)
```
> Fix for segmentation fault with tilde:

- gsi_openssh/source/ssh-rsa.c
- travis-ci/build_and_test.sh
- travis-ci/run_task_inside_docker.sh
As per https://github.com/gridcf/gct/pull/154#issuecomment-894463701 and following comments, this PR should fix the build problems introduced with #154.
Again much thanks to @msalle for providing a patch that makes GSI-OpenSSH w/HPN 8.6p1 compile with OpenSSL version 1.0.x (as shipped with CentOS 7, which is used on Travis CI for our build tests).
> Fix for gsi openssh builds on centos 7

- gsi/openssl_error/source/configure.ac
- gsi/openssl_error/source/library/globus_error_openssl.c
- gsi_openssh/source/dh.c
- gsi_openssh/source/fips_mode_replacement.h
- gsi_openssh/source/kex.c
- gsi_openssh/source/kexgexc.c
- gsi_openssh/source/readconf.c
- gsi_openssh/source/servconf.c
- gsi_openssh/source/ssh-keygen.c
- gsi_openssh/source/ssh.c
- gsi_openssh/source/sshconnect2.c
- gsi_openssh/source/sshd.c
- gsi_openssh/source/sshkey.c
- packaging/debian/globus-gsi-openssl-error/debian/changelog.in
- packaging/fedora/globus-gsi-openssl-error.spec
OpenSSL 3.0 beta2 has removed a few functions:
- `ERR_GET_FUNC()` is no longer there and there is no simple replacement, so we best just comment out the one place it occurs.
- gsi_openssh (which we now include) uses `FIPS_mode()` which no longer exists in 3.0. Also here there is no easy replacement, since FIPS mode is quite differently enabled in 3.0. We add a macro via the new `fips_mode_replacement.h` that simply returns 0.
> More OpenSSL3.0 fixes, for 3.0-beta2

- myproxy/source/configure.ac
- myproxy/source/man/myproxy-server.config.5
- myproxy/source/myproxy-server.config
- myproxy/source/myproxy-test
- myproxy/source/myproxy-test-replicate
- myproxy/source/myproxy.c
- myproxy/source/safe_is_path_trusted.c
- myproxy/source/voms_utils.h
- packaging/debian/myproxy/debian/changelog.in
- packaging/fedora/myproxy.spec
Fix for #160. As proposed in https://github.com/gridcf/gct/issues/160#issuecomment-901860742.
> Use -l (--listen) flag when starting myproxy-server in test scripts

- gsi/openssl_error/source/configure.ac
- gsi/openssl_error/source/test/globus_openssl_error_test.stdout
- packaging/debian/globus-gsi-openssl-error/debian/changelog.in
- packaging/fedora/globus-gsi-openssl-error.spec
Function names are (null) in OpenSSL 3.0 - adapt expected test output.
> One more openssl 3.0 fix

- myproxy/source/configure.ac
- myproxy/source/ssl_utils.c
- packaging/debian/myproxy/debian/changelog.in
- packaging/fedora/myproxy.spec
Make check succeeds on Fedora 36 with this change.
Fixes #171.
> OpenSSL 3.0 compatibility

- .github/workflows/build-test-deploy.yml
This should enable GHA CI builds after merging pull requests. Before this change GHA CI builds only happened when:
* a tag ([with special format](https://github.com/gridcf/gct/blob/41c255119dcbdbd8bd12d28d8f187df96bc0ec27/.github/workflows/build-test-deploy.yml#L5-L7)) was created (and pushed)
* a pull request was created
> Enable GHA CI builds also for pushes to the master branch

- gsi/cert_utils/source/configure.ac
- gsi/cert_utils/source/programs/grid-cert-request.in
- packaging/debian/globus-gsi-cert-utils/debian/changelog.in
- packaging/fedora/globus-gsi-cert-utils.spec
$ grid-cert-request --dir tmp
Enter your name, e.g., John Smith: NN
A certificate request and private key is being created.
You will be asked to enter a PEM pass phrase.
This pass phrase is akin to your account password,
and is used to protect your key file.
If you forget your pass phrase, you will need to
obtain a new certificate.
Can't load /var/adm/wtmp into RNG
80EB3915197F0000:error:12000079:random number generator:RAND_load_file:Cannot open file:crypto/rand/randfile.c:106:Filename=/var/adm/wtmp
Can't load /var/log/messages into RNG
80EB3915197F0000:error:12000079:random number generator:RAND_load_file:Cannot open file:crypto/rand/randfile.c:106:Filename=/var/log/messages
Error number 1 was returned by
/usr/bin/openssl
> Can't use non-existing or non-accessible files as source for random data

- gsi/cert_utils/source/configure.ac
- gsi/cert_utils/source/library/globus_gsi_cert_utils.c
- gsi/cert_utils/source/library/globus_gsi_cert_utils.h
- gsi/credential/source/configure.ac
- gsi/credential/source/library/globus_gsi_cred_handle.c
- packaging/debian/globus-gsi-cert-utils/debian/changelog.in
- packaging/debian/globus-gsi-credential/debian/changelog.in
- packaging/fedora/globus-gsi-cert-utils.spec
- packaging/fedora/globus-gsi-credential.spec
By using `ASN1_TIME_diff()` instead of manually parsing the data, we make `globus_gsi_cert_utils_make_time()` a lot simpler and also work for `ASN1_GENERALIZEDTIME` and not just `ASN1_UTCTIME` (i.e. it can use `ASN1_TIME`). `ASN1_TIME_diff()` requires OpenSSL >= 1.0.2.
Also rework `globus_gsi_cred_get_lifetime()` to just use `time(NULL)` to get the current UNIX timestamp which means it no longer needs `globus_gsi_cert_utils_make_time()`.
This fixes issue #208
> Replace make_time function to work after 2050

- gsi_openssh/source/fips_mode_replacement.h
- gsi_openssh/source/kexgex.c
- gsi_openssh/source/kexgexc.c
Fixes #207
****
Looking at https://github.com/gridcf/gct/actions/runs/3940255855/jobs/6780376794#step:3:13057 this interestingly now also affects our builds on ~Rocky Linux~ CentOS Stream 9 ~(and most likely also CentOS Stream 9)~ - it didn't in the past runs. I don't know why this starts to happen now, maybe a change in the used OpenSSL on these distributions.
****
Corrected: I misread things at first.
> Add missing header file

- myproxy/source/configure.ac
The SASL and LDAP version checks called exit without including <stdlib.h>.  Future compilers will not support implicit function declarations, causing these two checks to fail unconditionally. Instead, return directly from the main function.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
Alternative to globus/globus-toolkit#132.
> configure.ac: Avoid calling the undeclared exit function

- common/source/configure.ac
- common/source/library/globus_libc.h
- common/source/library/globus_libc_setenv.c
- packaging/debian/globus-common/debian/changelog.in
- packaging/fedora/globus-common.spec
~~~
/usr/include/globus/globus_libc.h:206:45: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
206 | int globus_libc_setenv(register const char *name,
|                                             ^~~~
/usr/include/globus/globus_libc.h:207:45: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
207 |                        register const char *value,
|                                             ^~~~~
/usr/include/globus/globus_libc.h:209:48: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
209 | void globus_libc_unsetenv(register const char *name);
|                                                ^~~~
~~~
> Remove register qualifier that is incompatible with C++17

- gram/rsl/source/configure.ac
- gram/rsl/source/dummy.c
- gram/rsl/source/globus_rsl.c
- packaging/debian/globus-rsl/debian/changelog.in
- packaging/fedora/globus-rsl.spec
The libglobus_rsl_assist library is an empty backwards compatibility library that is there to fulfil link dependencies from earlier versions of GT/GCT. The functionality that used to be provided by this library now is in libglobus_rsl. When linking the libglobus_rsl_assist library it links to libglobus_rsl (-lglobus_rsl), so that loading the empty compatibility library will load the globus_rsl library. However, many Linux distribution by default uses -Wl,--as-needed when linking during package builds (rpm/dpkg). This means that the link from libglobus_rsl_assist to libglobus_rsl is lost. This commit adds a dummy function that references a symbol in the libglobus_rsl library so that the link information is not removed when linking using -Wl,--as-needed.
In addition this commit declares the …
> Make library linking survive -Wl,--as-needed

- gsi/sysconfig/source/configure.ac
- gsi/sysconfig/source/library/globus_gsi_system_config.c
- packaging/debian/globus-gsi-sysconfig/debian/changelog.in
- packaging/fedora/globus-gsi-sysconfig.spec
> Remove extra comma

- gass/copy/source/configure.ac
- gass/copy/source/globus_gass_copy_glob.c
- packaging/debian/globus-gass-copy/debian/changelog.in
- packaging/fedora/globus-gass-copy.spec
> Checksum error checks fixes #215

- myproxy/source/auth_pam.c
- myproxy/source/configure.ac
- myproxy/source/myproxy_sasl_client.c
- myproxy/source/myproxy_sasl_server.c
- myproxy/source/plugin_common.c
- packaging/debian/myproxy/debian/changelog.in
- packaging/fedora/myproxy.spec
Fedora 40 updated gcc to version 14. This version is more strict with assignments between different pointer types. This PR fixes the compilation errors in myproxy due to this change.
The PR has two commits. The first has no code changes, only changes to tabs and spaces. The second commit has the actual code changes.
> Type errors

- gridftp/server-lib/src/configure.ac
- gridftp/server-lib/src/test/globus_ftp_telnet_client.c
- packaging/debian/globus-gridftp-server-control/debian/changelog.in
- packaging/fedora/globus-gridftp-server-control.spec
Reported to Debian Bug Tracking System (BTS):
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1075012
```
globus_ftp_telnet_client.c:100:58: error: passing argument 5 of ‘globus_xio_readv’ from incompatible pointer type [-Wincompatible-pointer-types]
100 |         res = globus_xio_readv(xio_handle, &readv, 1, 1, &len, NULL);
|                                                          ^~~~
|                                                          |
|                                                          int *
In file included from globus_ftp_telnet_client.c:17:
/usr/include/globus/globus_xio.h:776:41: note: expected ‘globus_size_t *’ {aka ‘long unsigned int *’} but argument is of type ‘int *’
776 |     globus_size_t *                     nbytes,
| …
```
> Passing argument from incompatible pointer type

- .github/workflows/build-test-deploy.yml
- .travis.yml
- travis-ci/make_rpms.sh
- travis-ci/make_source_tarballs.sh
- travis-ci/run_task_inside_docker.sh
> Retire CentOS 7 and CentOS Stream 8 for our CIs

- packaging/fedora/myproxy.spec
The ENGINE API is deprecated in openssl since version 3.0. Fedora is trying to phase it out, and as a first step they have moved the associated header files into a separete package. For now the ENGINE API can still be used if this package is added to the build requriements for the package, as this commit does. Developers are encouraged to use the PROVIDER API instead.
https://fedoraproject.org/wiki/Changes/OpensslDeprecateEngine
> Add openssl-devel-engine build requirement on Fedora 41+

- myproxy/source/ssl_utils.c
As per #229 MyProxy still used an old cipher for encrypting private keys. Changes courtesy of Mischa Salle (@msalle).
Fixes #229.
> MyProxy: change private key cipher to EVP_aes_256_cbc()

- travis-ci/run_task_inside_docker.sh
As per https://github.com/gridcf/gct/actions/runs/11596619308/job/32288101813?pr=232#step:4:155 there is currently an issue in the Rocky Linux 9 container that already showed two times now:
The repo data inside the container seems to be stale and not current with the actual repos for the package "python3-devel (at "3.9.18-3.el9_4.5")" and its dependencies. https://download.rockylinux.org/pub/rocky/9/AppStream/x86_64/os/Packages/p/ shows python3-devel at "3.9.18-3.el9_4.6" since "24-Oct-2024 18:30" making the tried-to-be-installed package out-of-date.
So let's update the repo data prior to installing packages.
> CI: update potentially stale repo data before trying to install packages

- common/source/configure.ac
- packaging/debian/globus-common/debian/changelog.in
- packaging/fedora/globus-common.spec
Fix for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1086241
> Compatibility with autoconf 2.72

- myproxy/source/certauth_extensions.c
- myproxy/source/certauth_extensions.h
- myproxy/source/configure.ac
- myproxy/source/myproxy_server.c
- packaging/debian/myproxy/debian/changelog.in
- packaging/fedora/myproxy.spec
OpenSSL in RHEL 10 has dropped the support for the ENGINE API.
This PR makes the use of the ENGINE API optional in myproxy. so that it can be compiled on RHEL+EPEL 10.
> Make OpenSSL engine optional

- gsi_openssh/source/configure.ac
Taking over upstream openssh commit 2eded551ba96e66bc3afbbcc883812c2eac02bd7:
> OpenSSL has moved to 3.4 which we don't currently accept.  Based on the OpenSSL versioning policy[0] it looks like all of the 3.x versions should work with OpenSSH, so remove the distinction in configure and accept all of them.
> 
> [0] https://openssl.org/policies/general/versioning-policy.html
Fixes #235
> Merge flags for OpenSSL 3.x versions.

- gridftp/server/src/configure.ac
- gridftp/server/src/globus_gridftp_server.h
- gridftp/server/src/test/sharing_allowed_test.c
- gsi/credential/source/configure.ac
- gsi/credential/source/library/globus_gsi_credential.c
- gsi/credential/source/library/globus_gsi_credential.h
- gsi/credential/source/library/globus_i_gsi_credential.h
- gsi/proxy/proxy_ssl/source/configure.ac
- gsi/proxy/proxy_ssl/source/library/proxycertinfo.h
- gsi/proxy/proxy_utils/source/configure.ac
- gsi/proxy/proxy_utils/source/programs/grid_proxy_init.c
- myproxy/source/certauth_extensions.c
- myproxy/source/configure.ac
- myproxy/source/gsi_socket.c
- myproxy/source/myproxy_server.c
- myproxy/source/ssl_utils.c
- packaging/debian/globus-gridftp-server/debian/changelog.in
- packaging/debian/globus-gsi-credential/debian/changelog.in
- packaging/debian/globus-gsi-proxy-ssl/debian/changelog.in
- packaging/debian/globus-proxy-utils/debian/changelog.in
- packaging/debian/myproxy/debian/changelog.in
- packaging/fedora/globus-gridftp-server.spec
- packaging/fedora/globus-gsi-credential.spec
- packaging/fedora/globus-gsi-proxy-ssl.spec
- packaging/fedora/globus-proxy-utils.spec
- packaging/fedora/myproxy.spec
GCC 15 has improved diagnostics and detects more incompatible pointer type errors than earlier versions. Especially function pointers being assigned pointers to function with the wrong type and/or number of arguments are better detected.
This commit fixes the compilation with GCC 15 on Fedora 42.
> Fix compilation with GCC 15 (Fedora 42)

- gram/jobmanager/source/configure.ac
- gram/jobmanager/source/globus_gram_job_manager_staging.c
- packaging/debian/globus-gram-job-manager/debian/changelog.in
- packaging/fedora/globus-gram-job-manager.spec
For relative paths stdout/stderr are relative to the job's working directory which is writable, so the check is redundant.
The current check instead tests if the user's home directory is writable which is irrelevant. The test also creates and leaves behind a zero-length file in the user's home directory. The test also gives false failures if the user's home directory is not writable.
Fixes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1103552
> Only check write permission for stdout/stderr if path is absolute
